

all:
	pdflatex ./SGX544_hwdoc.tex

clean:
	rm *.log *.aux *.synctex.gz *.out *.toc *.bbl *.blg *.lof *.gz *.fls *.lot *.fdb_latexmk *.tex.bak

cleanall:
	rm SGX544_hwdoc.pdf
	rm *.log *.aux *.synctex.gz *.out *.toc *.bbl *.blg *.lof *.gz *.fls *.lot *.fdb_latexmk *.tex.bak
